#if defined(SINGLE)
#define _ESMF_KIND_RX _ESMF_KIND_R4
#define ESMF_KIND_RX ESMF_KIND_R4
#define ESMF_TYPEKIND_RX ESMF_TYPEKIND_R4
#else
#define _ESMF_KIND_RX _ESMF_KIND_R8
#define ESMF_KIND_RX ESMF_KIND_R8
#define ESMF_TYPEKIND_RX ESMF_TYPEKIND_R8
#endif


#define COAMPS_MASK_INLAND_WATER -1
#define COAMPS_MASK_WATER         0
#define COAMPS_MASK_LAND          1
#define COAMPS_MASK_FROZEN_WATER  2
#define COAMPS_MASK_FROZEN_LAND   3
