version: 2.1

jobs:

  build-base-images:
    docker:
      - image: cimg/base:2020.01
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Checkout Code (ESCOMP-Containers)
          command: git clone --depth 1 https://github.com/ESCOMP/ESCOMP-Containers.git
      - run:
          name: Checkout Code (ESMF)
          command: git clone --branch $CIRCLE_BRANCH --depth 1 https://github.com/esmf-org/esmf.git
      - run:
          name: Docker Build
          command: docker build -t "esmf/centos8" --file "ESCOMP-Containers/base/centos8/Dockerfile" .
      - run:
          name: Docker Push
          command: bash esmf/.circleci/sh/docker-push-generic.sh "esmf/centos8"
      - run:
          name: Docker Build esmf-doc-base
          command: docker build -t "esmf/esmf-doc-base" --file "ESCOMP-Containers/ESMF/doc/esmf-doc-base/Dockerfile" --build-arg DOCKER_NAMESPACE="esmf" .
      - run:
          name: Docker Push esmf-doc-base
          command: bash esmf/.circleci/sh/docker-push-generic.sh "esmf/esmf-doc-base"
      - run:
          name: Docker Build esmpy-doc-base
          command: docker build -t "esmf/esmpy-doc-base" --file "ESCOMP-Containers/ESMF/doc/esmpy-doc-base/Dockerfile" --build-arg DOCKER_NAMESPACE="esmf" .
      - run:
          name: Docker Push esmpy-doc-base
          command: bash esmf/.circleci/sh/docker-push-generic.sh "esmf/esmpy-doc-base"

  build-escomp-esmf:
    docker:
      - image: cimg/base:2020.01
    resource_class: xlarge
    steps:
      - setup_remote_docker
      - run:
          name: Checkout Code (ESCOMP-Containers)
          command: git clone --depth 1 https://github.com/ESCOMP/ESCOMP-Containers.git
      - run:
          name: Checkout Code (ESMF)
          command: git clone --branch $CIRCLE_BRANCH --depth 1 https://github.com/esmf-org/esmf.git
      - run:
          name: Docker Build
          command: docker build -t "esmf/esmf:${CIRCLE_BRANCH}" --file "ESCOMP-Containers/ESMF/dev/Dockerfile" --build-arg ESMF_BRANCH="${CIRCLE_BRANCH}" --build-arg DOCKER_NAMESPACE="esmf" .
      - run:
          name: Docker Push
          command: bash esmf/.circleci/sh/docker-push-generic.sh "esmf/esmf:${CIRCLE_BRANCH}"
      - run:
          name: Extract Artifacts
          command: bash esmf/.circleci/sh/extract-artifacts.sh "/tmp" "/tmp/artifacts.zip" "esmf/esmf:${CIRCLE_BRANCH}"
      - store_artifacts:
          path: /tmp/artifacts

  should-run-linux:
    docker:
      - image: cimg/base:2020.01
    resource_class: small
    steps:
      - run: exit 0

  should-run-nuopc-protos:
    docker:
      - image: cimg/base:2020.01
    resource_class: small
    steps:
      - run: exit 0

  should-build-docs:
    docker:
      - image: cimg/base:2020.01
    resource_class: small
    steps:
      - run: exit 0
      
  should-run-test-coverage:
    docker:
      - image: cimg/base:2020.01
    resource_class: small
    steps:
      - run: exit 0
  
  should-run-api-change:
    docker:
      - image: cimg/base:2020.01
    resource_class: small
    steps:
      - run: exit 0

  should-run-osx:
    docker:
      - image: cimg/base:2020.01
    resource_class: small
    steps:
      - run: exit 0

  build-run-tests:
    parameters:
      target:
        type: string
    docker:
      - image: esmf/esmf:$CIRCLE_BRANCH
    resource_class: xlarge
    environment:
      - ESMF_ARTIFACTS: /artifacts
      - ESMF_OUTDIR: /artifacts/test-artifacts
    steps:
      - run:
          name: Checkout Code (ESCOMP-Containers)
          command: git clone --depth 1 https://github.com/ESCOMP/ESCOMP-Containers.git
      - run:
          name: Checkout Code (ESMF)
          command: git clone --branch $CIRCLE_BRANCH --depth 1 https://github.com/esmf-org/esmf.git
      - run:
          name: Create Artifacts Directory
          command: mkdir -p $ESMF_OUTDIR
      - run:
          name: make build_<< parameters.target >>
          command: cd $ESMF_DIR && make build_<< parameters.target >> 2>&1 | tee $ESMF_OUTDIR/esmf-make-build_<< parameters.target >>.out
      - run:
          name: make run_<< parameters.target >>
          command: cd $ESMF_DIR && make run_<< parameters.target >> 2>&1 | tee $ESMF_OUTDIR/esmf-make-run_<< parameters.target >>.out
      - run:
          name: Collect Artifacts
          command: bash $ESMF_DIR/.circleci/sh/collect-test-artifacts.sh << parameters.target >>
          when: always
      - store_artifacts:
          path: /artifacts/test-artifacts.zip
          destination: << parameters.target >>-artifacts.zip

  build-esmf-docs:
    docker:
      - image: cimg/base:2020.01
    steps:
      - setup_remote_docker
      - run:
         name: "Removing slash from branch name "
         command: |
                  echo 'export CIRCLE_BRANCH_NEW=`echo ${CIRCLE_BRANCH} | sed 's#/#_#'`' >> $BASH_ENV
                  echo $CIRCLE_BRANCH_NEW
                  source $BASH_ENV
      - run:
          name: Checkout Code (ESCOMP-Containers)
          command: git clone --depth 1 https://github.com/ESCOMP/ESCOMP-Containers.git
      - run:
          name: Checkout Code (ESMF)
          command: git clone --branch $CIRCLE_BRANCH  --depth 1 https://github.com/esmf-org/esmf.git
      - run:
          name: Docker Build esmf-doc
          command: docker build -t "esmf/esmf-doc:${CIRCLE_BRANCH_NEW}" --file "ESCOMP-Containers/ESMF/doc/esmf-doc/Dockerfile" --build-arg ESMF_BRANCH="${CIRCLE_BRANCH}" --build-arg DOCKER_NAMESPACE="esmf" --no-cache .
      - run:
          name: Extract Artifacts
          command: bash esmf/.circleci/sh/extract-artifacts.sh "/tmp/artifacts" "/artifacts/doc-artifacts.zip" "esmf/esmf-doc:${CIRCLE_BRANCH_NEW}"
      - save_cache:
          key: esmf-docs-{{ .Revision }}
          paths:
            - /tmp/artifacts
            - esmf
      - store_artifacts:
          path: /tmp/artifacts/doc-artifacts.zip
          destination: doc-artifacts.zip

  publish-esmf-docs:
    machine: true
    resource_class: medium
    steps:
      - restore_cache:
          keys:
            - esmf-docs-{{ .Revision }}
      - run:
          name: Prep Artifacts
          command: cd /tmp/artifacts && unzip doc-artifacts.zip
      - run:
          name: Push to github.io
          command: bash esmf/.circleci/sh/doc-push.sh
          
  run-test-coverage:
    docker:
      - image: cimg/base:2020.01
    steps:
      - setup_remote_docker
      - run:
         name: "Removing slash from branch name "
         command: |
                  echo 'export CIRCLE_BRANCH_NEW=`echo ${CIRCLE_BRANCH} | sed 's#/#_#'`' >> $BASH_ENV
                  echo $CIRCLE_BRANCH_NEW
                  source $BASH_ENV
      - run:
          name: Checkout Code (ESCOMP-Containers)
          command: git clone --depth 1 https://github.com/ESCOMP/ESCOMP-Containers.git
      - run:
          name: Checkout Code (ESMF)
          command: git clone --branch $CIRCLE_BRANCH --depth 1 https://github.com/esmf-org/esmf.git
      - run:
          name: Docker Run Test Coverage
          command: docker build -t "esmf/test-coverage:${CIRCLE_BRANCH_NEW}" --file "ESCOMP-Containers/ESMF/test_coverage/Dockerfile" --build-arg ESMF_BRANCH="${CIRCLE_BRANCH}" --build-arg DOCKER_NAMESPACE="esmf" --no-cache .
      - run:
          name: Extract Test Coverage
          command: bash esmf/.circleci/sh/extract-artifacts.sh "/tmp/artifacts" "/artifacts/test_coverage-artifacts.zip" "esmf/test-coverage:${CIRCLE_BRANCH_NEW}"
      - save_cache:
          key: test-coverage-{{ .Revision }}
          paths:
            - /tmp/artifacts
            - esmf
      - store_artifacts:
          path: /tmp/artifacts/test_coverage-artifacts.zip
          destination: test_coverage-artifacts.zip

  publish-test-coverage:
    machine: true
    resource_class: medium
    steps:
      - restore_cache:
          keys:
            - test-coverage-{{ .Revision }}
      - run:
          name: Prep Test Coverage
          command: cd /tmp/artifacts && unzip test_coverage-artifacts.zip
      - run:
          name: Push to esmf-test-artifacts
          command: bash esmf/.circleci/sh/test_coverage-push.sh

  run-api-change:
    docker:
      - image: cimg/base:2020.01
    steps:
      - setup_remote_docker
      - run:
         name: "Removing slash from branch name "
         command: |
                  echo 'export CIRCLE_BRANCH_NEW=`echo ${CIRCLE_BRANCH} | sed 's#/#_#'`' >> $BASH_ENV
                  echo $CIRCLE_BRANCH_NEW
                  source $BASH_ENV
      - run:
          name: Checkout Code (ESCOMP-Containers)
          command: git clone --depth 1 https://github.com/ESCOMP/ESCOMP-Containers.git
      - run:
          name: Checkout Code (ESMF)
          command: git clone --branch $CIRCLE_BRANCH https://github.com/esmf-org/esmf.git
      - run:
          name: Docker Run API Changes
          command: docker build -t "esmf/api-change:${CIRCLE_BRANCH_NEW}" --file "ESCOMP-Containers/ESMF/API_changes/Dockerfile" --build-arg DOCKER_NAMESPACE="esmf" --build-arg TAG1="ESMF_8_1_0" --build-arg TAG2="${CIRCLE_BRANCH}" --no-cache .
      - run:
          name: Extract API Changes
          command: bash esmf/.circleci/sh/extract-artifacts.sh "/tmp/artifacts" "/artifacts/api_change-artifacts.zip" "esmf/api-change:${CIRCLE_BRANCH_NEW}"
      - save_cache:
          key: api-change-{{ .Revision }}
          paths:
            - /tmp/artifacts
            - esmf
      - store_artifacts:
          path: /tmp/artifacts/api_change-artifacts.zip
          destination: api_change-artifacts.zip

  publish-api-change:
    machine: true
    resource_class: medium
    steps:
      - restore_cache:
          keys:
            - api-change-{{ .Revision }}
      - run:
          name: Prep API Changes
          command: cd /tmp/artifacts && unzip api_change-artifacts.zip
      - run:
          name: Push to esmf-test-artifacts
          command: bash esmf/.circleci/sh/api_changes-push.sh

  esmpy-test:
    parameters:
      target:
        type: string
    docker:
      - image: esmf/esmf:$CIRCLE_BRANCH
    steps:
      - run:
          name: python setup.py test<< parameters.target>>
          command: cd ${ESMPY_DIR} && python setup.py test<< parameters.target>>
      - run:
          name: Prep Test Results
          command: mkdir -p /tmp/test-results && mv ${ESMF_DIR}/src/addon/ESMPy/nosetests.xml /tmp/test-results/
          when: always
      - store_test_results:
          path: /tmp/test-results

  build-esmpy-docs:
    docker:
      - image: cimg/base:2020.01
    steps:
      - setup_remote_docker
      - run:
         name: "Removing slash from branch name "
         command: |
                  echo 'export CIRCLE_BRANCH_NEW=`echo ${CIRCLE_BRANCH} | sed 's#/#_#'`' >> $BASH_ENV
                  echo $CIRCLE_BRANCH_NEW
                  source $BASH_ENV
      - run:
          name: Checkout Code (ESCOMP-Containers)
          command: git clone --depth 1 https://github.com/ESCOMP/ESCOMP-Containers.git
#          command: git clone --depth 1 --branch esmpy-doc-base-to-ubuntu https://github.com/esmf-org/ESCOMP-Containers.git
      - run:
          name: Checkout Code (ESMF)
          command: git clone --branch $CIRCLE_BRANCH --depth 1 https://github.com/esmf-org/esmf.git
      - run:
          name: Docker Build esmpy-doc
          command: docker build -t "esmf/esmpy-doc:${CIRCLE_BRANCH_NEW}" --file "ESCOMP-Containers/ESMF/doc/esmpy-doc/Dockerfile" --build-arg ESMF_BRANCH="${CIRCLE_BRANCH}" --build-arg DOCKER_NAMESPACE="esmf" --no-cache .
      - run:
          name: Extract Doc Artifacts
          command: bash esmf/.circleci/sh/extract-artifacts.sh "/tmp/artifacts" "/artifacts/doc-esmpy.zip" "esmf/esmpy-doc:${CIRCLE_BRANCH_NEW}"
      - save_cache:
          key: esmpy-docs-{{ .Revision }}
          paths:
            - /tmp/artifacts
            - esmf
      - store_artifacts:
          path: /tmp/artifacts/doc-esmpy.zip
          destination: doc-esmpy.zip

  publish-esmpy-docs:
    machine: true
    resource_class: medium
    steps:
      - restore_cache:
          keys:
            - esmpy-docs-{{ .Revision }}
      - run:
          name: Prep Artifacts
          command: cd /tmp/artifacts && unzip doc-esmpy.zip
      - run:
          name: Push to github.io
          command: bash esmf/.circleci/sh/doc-push-esmpy.sh

  osx-esmf:
    macos:
      xcode: "11.3.1"
#    resource_class: large
    steps:
      - run:
          name: Checkout Code
          command: cd && git clone --branch $CIRCLE_BRANCH --depth 1 https://github.com/esmf-org/esmf.git esmf
      - restore_cache:
          keys:
            - osx-cache-10
#      - run:
#          name: Create Brew Environment
#          command: bash ~/esmf/.circleci/sh/osx/osx-brew-install.sh
      - run:
          name: Create Conda Environment
          command: bash ~/esmf/.circleci/sh/osx/osx-conda.sh
      - save_cache:
          key: osx-cache-10
          paths:
            - ~/miniconda
#            - /usr/local/Cellar
      - run:
          name: make info
          command: bash ~/esmf/.circleci/sh/osx/osx-make-funcs.sh "info"
      - run:
          name: make
          command: bash ~/esmf/.circleci/sh/osx/osx-make-funcs.sh "make"
      - run:
          name: make install
          command: bash ~/esmf/.circleci/sh/osx/osx-make-funcs.sh "install"
#      - run:
#          name: make check
#          command: bash ~/esmf/.circleci/sh/osx/osx-make-funcs.sh "check"
      - run:
          name: Collect Test Artifacts
          command: bash ~/esmf/.circleci/sh/osx/osx-make-funcs.sh "collect-test-results"
          when: always
      - store_artifacts:
          path: /tmp/osx-artifacts.zip
          destination: osx-artifacts.zip

  nuopc-app-prototypes:
    docker:
      - image: cimg/base:2020.01
    resource_class: xlarge
    steps:
      - setup_remote_docker
      - run:
          name: Checkout Code (ESCOMP-Containers)
          command: git clone --depth 1 https://github.com/ESCOMP/ESCOMP-Containers.git
#          command: git clone --depth 1 --branch esmpy-doc-base-to-ubuntu https://github.com/esmf-org/ESCOMP-Containers.git
      - run:
          name: Checkout Code (ESMF)
          command: git clone --branch $CIRCLE_BRANCH --depth 1 https://github.com/esmf-org/esmf.git
      - run:
          name: Docker Build
          command: cd ESCOMP-Containers/ESMF/nuopc-app-prototypes && docker build -t "esmf/nuopc-app-prototypes" --build-arg ESMF_BRANCH="${CIRCLE_BRANCH}" --build-arg DOCKER_NAMESPACE="esmf" --no-cache .
      - run:
          name: Run NUOPC Prototypes
          command: bash esmf/.circleci/sh/run-nuopc-protos.sh
      - run:
          name: Run NUOPC Prototypes Meta Tests
          command: docker exec -t runner /opt/docker-entrypoint.sh meta_test
      - run:
          name: Prep Artifacts
          command: docker exec -t runner /opt/docker-entrypoint.sh prep_artifacts && docker commit runner esmf/nuopc-app-prototypes && docker stop runner && docker rm runner
          when: always
      - run:
          name: Extract Artifacts
          command: bash esmf/.circleci/sh/extract-artifacts.sh /tmp /opt/artifacts.zip esmf/nuopc-app-prototypes && cd /tmp && unzip /tmp/artifacts.zip
          when: always
      - store_artifacts:
          path: /tmp/artifacts.zip
          destination: artifacts.zip
      - store_test_results:
          path: /tmp/artifacts/meta_test

# =============================================================================

workflows:

  build-and-test-commit:
    jobs:
      - should-run-linux:
          type: approval
      - build-escomp-esmf:
          requires:
            - should-run-linux
      - build-run-tests:
          name: build-run-commit-<< matrix.target >>
          matrix:
            parameters:
              target: ["unit_tests", "system_tests", "examples"]
          requires:
            - build-escomp-esmf
      - esmpy-test:
          name: esmpy-test<< matrix.target >>
          matrix:
            parameters:
              target: ["", "_parallel", "_examples", "_examples_parallel"]
          requires:
            - build-escomp-esmf
      - should-run-nuopc-protos:
          type: approval
          requires:
            - build-escomp-esmf
      - nuopc-app-prototypes:
          requires:
            - should-run-nuopc-protos
#      - osx-esmf

#  build-and-test-nightly:
#    triggers:
#      - schedule:
#          cron: "0 3 * * *"
#          filters:
#            branches:
#              only:
#                - develop
#    jobs:
#      - build-base-images
#      - build-escomp-esmf:
#          requires:
#            - build-base-images
#      - build-run-tests:
#          name: build-run-<< matrix.target >>
#          matrix:
#            parameters:
#              target: ["unit_tests", "system_tests", "examples"]
#          requires:
#            - build-escomp-esmf
#      - esmpy-test:
#          name: esmpy-test<< matrix.target >>
#          matrix:
#            parameters:
#              target: ["", "_parallel", "_examples", "_examples_parallel"]
#          requires:
#            - build-escomp-esmf
#      - nuopc-app-prototypes:
#          requires:
#            - build-escomp-esmf
##      - osx-esmf

  docs-commit:
    jobs:
      - should-build-docs:
          type: approval
      - build-esmf-docs:
          requires:
            - should-build-docs
      - publish-esmf-docs:
          requires:
            - build-esmf-docs
#          filters:
#            branches:
#              only:
#                - develop
      - build-esmpy-docs:
          requires:
            - should-build-docs
      - publish-esmpy-docs:
          requires:
            - build-esmpy-docs
#          filters:
#            branches:
#              only:
#                - develop
  test-coverage-commit:
    jobs:
      - should-run-test-coverage:
         type: approval
      - run-test-coverage:
          requires:
            - should-run-test-coverage
      - publish-test-coverage:
          requires:
            - run-test-coverage
#          filters:
#            branches:
#              only:
#                - develop  

  api-change-commit:
    jobs:
      - should-run-api-change:
         type: approval
      - run-api-change:
          requires:
            - should-run-api-change
      - publish-api-change:
          requires:
            - run-api-change
#          filters:
#            branches:
#              only:
#                - develop

#  osx-commit:
#    jobs:
#      - should-run-osx:
#          type: approval
#      - osx-esmf:
#          requires:
#            - should-run-osx
