language: generic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-6
before_script:
  - FC=gfortran-6 cmake .
  - make
script:
  - ctest
notifications:
  email: false
